// ====================================================================
// Yann COLLETTE
// Copyright 2009
// This file is released into the public domain
// ====================================================================
demopath = get_absolute_file_path('fann_toolbox.dem.gateway.sce');

subdemolist = ['Cascade training',     'cascade_train.sce'; ...
               'Mushroom',             'mushroom.sce'; ...
               'Unit test',            'unit_test.sce'; ...
               'Robot',                'robot.sce'; ...
               'Scaling - Train part', 'scaling_train.sce'; ...
               'Scaling - Test part',  'scaling_test.sce'; ...
               'Steepness training',   'steepness_train.sce'; ...
               'Momentums',            'momentums.sce'; ...
               'Sample training',      'sample_training.sce'; ...
               'Simple - Train part',  'simple_train.sce'; ...
               'Simple - Test part',   'simple_test.sce'; ...
               'Train on data',        'train_on_data.sce'; ...
               'XOR - Train part',     'xor_train.sce'; ...
               'XOR - Test part',      'xor_test.sce'];

subdemolist(:,2) = demopath + subdemolist(:,2);
// ====================================================================

