// This file is released into the public domain
// Generated by builder.sce: Please, do not edit this file

try
 getversion("scilab");
catch
 error("Scilab 5.0 or more is required.");
end;

exec(get_absolute_file_path("loader.sce")+"etc/"+"serialize.start");
