// ------------------------------------------------------
// generated by builder.sce: Please do not edit this file
// cleaner.sce
// ------------------------------------------------------
curdir = pwd();
cleaner_path = get_file_path('cleaner.sce');
chdir(cleaner_path);
// ------------------------------------------------------
if fileinfo('loader.sce') <> [] then
  mdelete('loader.sce');
end
// ------------------------------------------------------
if fileinfo('Makelib.mak') <> [] then
  unix_s('nmake /Y /nologo /f Makelib.mak clean');
  mdelete('Makelib.mak');
end
// ------------------------------------------------------
if fileinfo('libcpowell.dll') <> [] then
  mdelete('libcpowell.dll');
end
// ------------------------------------------------------
if fileinfo('libcpowell.c') <> [] then
  mdelete('libcpowell.c');
end
// ------------------------------------------------------
chdir(curdir);
// ------------------------------------------------------
