// ------------------------------------------------------
// generated by builder.sce: Please do not edit this file
// ------------------------------------------------------

libcpowell_path = get_file_path('loader.sce');
list_functions = [             'newuoa';
];
addinter(libcpowell_path+'/libcpowell.dll','libcpowell',list_functions);
// remove temp. variables on stack
clear libcpowell_path;
clear list_functions;
clear get_file_path;
// ------------------------------------------------------
